<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <button id="btn">按钮</button>
  <ul></ul>
  <script>
    //微任务中有宏任务  
    /* Promise.reject().then(() => {
      console.log(3);
      setTimeout(() => {
        console.log(1);
      });
    }, () => Promise.reject()).catch(() => console.log(4))
    // Promise.resolve().then(() => {
    //   console.log(2);
    // }) */

    //   需求: 要执行一个异步操作,
    //     异步操作执行之后,
    //     要拿到异步操作的结果,
    //     然后根据结果,
    //     将数据渲染到页面上
    // btn.onclick = function () {
    //   setTimeout(() => {
    //     let arr = [1, 2, 3, 4]
    //     arr.forEach((item) => {
    //       oUl.innerHTML += `<li>${item}</li>`;
    //     })
    //   }, 1000);
    // }
    const oUl = document.querySelector('ul');

    btn.onclick = async function () {
      //先要请求到数据才能渲染页面
      //如果请求数据失败 那么下面的代码也不执行 提高用户体验 给用户一点提示 
      //解决方法: 使用try..catch方法
      try {
        //如果成功 下面的代码正常执行  如果失败则执行catch里面的代码
        let data = await getData()
        console.log(data);
        data.forEach(item => {
          oUl.innerHTML += `<li>${item}</li>`
        })
      } catch (error) {
        console.log(error);
        document.body.innerHTML = `<h1>网络请求失败,请稍后再试</h1>`
      }

    }
    function getData() {
      //返回一个promise对象 settimeout模拟异步请求数据
      return new Promise(resolve => {
        setTimeout(() => {
          console.log(1);
          console.log(a);
          let arr = [1, 2, 3, 4]
          resolve(arr)
        }, 1000);
      })
    }
  </script>
</body>

</html>